nationalarchives/tdr-notifications

src/main/scala/uk/gov/nationalarchives/scannotifications/messages/EventMessages.scala
src/test/scala/uk/gov/nationalarchives/scannotifications/LambdaSpec.scala
src/test/scala/uk/gov/nationalarchives/scannotifications/LambdaSpecUtils.scala

Some of the test cases include examples where emails and Slack alerts should _not_ be sent, e.g. because the ECR scan does not contain any vulnerabilities.
Before splitting the tests, these test cases were checking the wrong thing because they were only checking whether an email with an empty body was not being sent, rather than any email at all.
I tested this change by deliberately introducing a bug into the Slack and email message code so that they sent an alert even if there were no vulnerabilities. This should cause some of the tests to fail, but they stayed green. If you do the same thing on this branch, the relevant tests do fail.
Fixing these tests caught a bug in the maintenance window alerts. It was trying to send an alert even if the backup succeeded. I've fixed this issue in …

Split tests to verify that the wrong alerts are not sent, and fix bug in maintenance window alerts

---

src/main/scala/uk/gov/nationalarchives/scannotifications/messages/EventMessages.scala
src/test/scala/uk/gov/nationalarchives/scannotifications/LambdaSpec.scala
src/test/scala/uk/gov/nationalarchives/scannotifications/LambdaSpecUtils.scala

This gives the dev team some guidance when fixing the alerts.

Add link from email and Slack alerts to dev manual

---

src/main/scala/uk/gov/nationalarchives/notifications/decoders/ExportStatusDecoder.scala
src/main/scala/uk/gov/nationalarchives/notifications/messages/EventMessages.scala
src/test/scala/uk/gov/nationalarchives/notifications/LambdaSpecUtils.scala

- Add environment to incoming json object and use it.
- Update tests to work with new slack message
- Also don't bother sending alerts for successful exports on integration because it's very spammy.

Add environment to export notification

---

README.md
src/main/scala/uk/gov/nationalarchives/notifications/LambdaRunner.scala

Add the `LambdaRunner` app which wraps the Lambda in some executable code with a test message. This lets developers run the full app end-to-end including all the API calls.

Add an app to let developers run the notifications locally

---

src/test/scala/uk/gov/nationalarchives/notifications/EcrScanIntegrationSpec.scala
src/test/scala/uk/gov/nationalarchives/notifications/ExportIntegrationSpec.scala
src/test/scala/uk/gov/nationalarchives/notifications/JenkinsBackupIntegrationSpec.scala
src/test/scala/uk/gov/nationalarchives/notifications/LambdaIntegrationSpec.scala

This makes the tests names clearer. For example:
```
should not send a Slack message for an ECR scan of 'intg' with no results
```
rather than:
```
should not send a slack message for event
{
"detail": {
"scan-status": "COMPLETE",
"repository-name": "yara-dependencies",
"image-tags" : ["intg"],
"finding-severity-counts": {
"CRITICAL": 0,
"HIGH": 0,
"MEDIUM": 0,
"LOW": 0
}
}
}
```
The second name is even harder to read in IntelliJ, because it only shows you the first line in the test panel.
This is particularly useful when a test fails, because IntelliJ can't navigate to the source of a parameterized test, so you couldn't work out which test case failed without interpreting the event yourself.

Add a description to all tests

---

project/Dependencies.scala
src/main/resources/application.conf
src/main/scala/uk/gov/nationalarchives/notifications/LambdaRunner.scala
src/main/scala/uk/gov/nationalarchives/notifications/decoders/ScanDecoder.scala
src/main/scala/uk/gov/nationalarchives/notifications/messages/EventMessages.scala
src/main/scala/uk/gov/nationalarchives/notifications/messages/Messages.scala
src/test/resources/application.conf
src/test/resources/ecr-findings/including-muted-vulnerability.json
src/test/resources/ecr-findings/informational.json
src/test/resources/ecr-findings/low-severity.json
src/test/resources/ecr-findings/mixed-severity.json
src/test/resources/ecr-findings/muted-vulnerability.json
src/test/resources/ecr-findings/no-findings.json
src/test/resources/ecr-findings/undefined-severity.json
src/test/scala/uk/gov/nationalarchives/notifications/EcrScanIntegrationSpec.scala
src/test/scala/uk/gov/nationalarchives/notifications/ExportIntegrationSpec.scala
src/test/scala/uk/gov/nationalarchives/notifications/JenkinsBackupIntegrationSpec.scala
src/test/scala/uk/gov/nationalarchives/notifications/LambdaErrorSpec.scala
src/test/scala/uk/gov/nationalarchives/notifications/LambdaIntegrationSpec.scala
src/test/scala/uk/gov/nationalarchives/notifications/LambdaSpecUtils.scala
src/test/scala/uk/gov/nationalarchives/notifications/MockEcrApi.scala

When an ECR scan event arrives, fetch the names of the vulnerabilities from the AWS API. Compare them with a list
of muted vulnerabilities, and only send an alert for ones which are not muted.
This helps us in the case where a low-severity vulnerability has been reported, but no fix is available yet. We can mute the vulnerability until the fix is available so that if any further alerts are sent, we know they need to be investigated.

Filter vulnerabilities using scan findings report

---

src/main/resources/application.conf
src/main/scala/uk/gov/nationalarchives/notifications/messages/EventMessages.scala
src/test/scala/uk/gov/nationalarchives/notifications/ExportIntegrationSpec.scala

These changes are to make the export slack notifications a little easier to read. It makes the message appear differently based on whether an export completed successfully or not whilst also keeping pertinent information. 
I have also edited the appropriate tests to reflect this change.

TDR-893 Make export Slack notifications clearer

---

src/main/scala/uk/gov/nationalarchives/notifications/LambdaRunner.scala

This will make it easier for others to test export slack notifications in future as others will not have to create these variables themselves. They can be swapped with the `ecrScanMessage` variable within the `  val inputStream = new ByteArrayInputStream(ecrScanMessage.getBytes)` line to successfully test export notifications locally.

Add export message variables and note as to their purpose

---

Jenkinsfile-deploy
Jenkinsfile-deploy-mgmt
Jenkinsfile-test

- Create separate deployments for management and other environments
- Add the build steps normally in the test job
- Hard code the lambda name
- Put the deploy job back
- Default the test file to the intg environment

Create separate deployments

---

src/main/scala/uk/gov/nationalarchives/notifications/messages/EventMessages.scala
src/test/scala/uk/gov/nationalarchives/notifications/ExportIntegrationSpec.scala

We don't normally enable these because they're very noisy and don't give much useful information, but they'll be helpful for the show and tell demonstation tomorrow.

Temporarily allow Slack notifications for exports on intg

---

src/main/scala/uk/gov/nationalarchives/notifications/messages/EventMessages.scala
src/test/scala/uk/gov/nationalarchives/notifications/ExportIntegrationSpec.scala

This reverts commit 929f1b13ac95a0d4b5c5c9656692a3c770bcea19.
It was a temporary commit to allow us to demo export notifications for a show and tell.
Marking the PR as draft until it's ready to merge.

Revert "Temporarily allow Slack notifications for exports on intg"

---

src/main/scala/uk/gov/nationalarchives/notifications/Lambda.scala
src/main/scala/uk/gov/nationalarchives/notifications/LambdaRunner.scala
src/main/scala/uk/gov/nationalarchives/notifications/decoders/DiskSpaceAlarmDecoder.scala
src/main/scala/uk/gov/nationalarchives/notifications/decoders/ExportStatusDecoder.scala
src/main/scala/uk/gov/nationalarchives/notifications/decoders/IncomingEvent.scala
src/main/scala/uk/gov/nationalarchives/notifications/decoders/KeycloakEventDecoder.scala
src/main/scala/uk/gov/nationalarchives/notifications/messages/EventMessages.scala
src/test/scala/uk/gov/nationalarchives/notifications/DiskSpaceAlarmIntegrationSpec.scala

There is a cloudwatch alarm set up which monitors the disk usage of the
Jenkins instances.
When the disk usage goes over a threshold or when it goes below the
threshold, a message is sent to slack.
The message contains the server (Jenkins or JenkinsProd), the threshold
and the either a tick or a warning symbol depending on where it's ALARM
or OK.

Add notification for disk alert messages

---

src/main/scala/uk/gov/nationalarchives/notifications/decoders/DiskSpaceAlarmDecoder.scala
src/main/scala/uk/gov/nationalarchives/notifications/messages/EventMessages.scala
src/test/scala/uk/gov/nationalarchives/notifications/DiskSpaceAlarmIntegrationSpec.scala

The cloudwatch alarm for Jenkins is set to show an error if it stops
receiving data from the Jenkins Cloudwatch agent. This is good in that
we get alerted if there is a problem with the agent but it's confusing
in that it says that the disk space is above 70% when it isn't.
I've changed this to put in a more sensible message if the problem is
missing data points. The only way is to check for a string in the reason
field but that's unlikely to change so we should be ok.

Create a separate alert message for no data points.

---

src/main/scala/uk/gov/nationalarchives/notifications/messages/EventMessages.scala
src/test/scala/uk/gov/nationalarchives/notifications/DiskSpaceAlarmIntegrationSpec.scala

If the alarm is because the disk space on Jenkins is too high, the slack
message has a link to the dev documentation about how to clear it. I've
not put this on the missing data or ok messages as it's not really
needed as there's nothing to do.
I've also put the Grafana url as a proper link with text to make it look
a bit better in the message.

Add a link to the clear disk space documentation if the disk space is too high

---

src/main/scala/uk/gov/nationalarchives/notifications/messages/EventMessages.scala
src/test/scala/uk/gov/nationalarchives/notifications/ExportIntegrationSpec.scala

The end-to-end tests use 0 byte files to test uploading, this causes issues for the Transform Engine. In reality 0 byte files would not be accepted by TDR
To provide control which transfers in the lower environments (integration and staging) use the transferring body name to filter the messages.
The end-to-end tests will use "mock" body names for their transfers. Using the body name will also allow developers and others to control whether a message is sent to the Transform Engine when using the lower environments.

Use transferring body to prevent sqs message send

---

src/main/resources/application.conf
src/main/scala/uk/gov/nationalarchives/notifications/messages/Messages.scala
src/test/resources/application.conf
src/test/scala/uk/gov/nationalarchives/notifications/EcrScanIntegrationSpec.scala
src/test/scala/uk/gov/nationalarchives/notifications/ExportIntegrationSpec.scala
src/test/scala/uk/gov/nationalarchives/notifications/KeycloakEventIntegrationSpec.scala
src/test/scala/uk/gov/nationalarchives/notifications/LambdaIntegrationSpec.scala
src/test/scala/uk/gov/nationalarchives/notifications/LambdaSpecUtils.scala
src/test/scala/uk/gov/nationalarchives/notifications/TransformEngineRetryIntegrationSpec.scala

Keycloak events are still sent to the main da-tdr channel.
I've also changed it so that only export events with a judgment
consignment type are sent to the judgments channel.
I've updated the tests to have a slack webhook parameter so we can check
they're being sent to the right places.

Send most messages to da-tdr-notifications.

---

src/main/scala/uk/gov/nationalarchives/notifications/Lambda.scala
src/main/scala/uk/gov/nationalarchives/notifications/LambdaRunner.scala
src/main/scala/uk/gov/nationalarchives/notifications/decoders/CloudwatchAlarmDecoder.scala
src/main/scala/uk/gov/nationalarchives/notifications/decoders/IncomingEvent.scala
src/main/scala/uk/gov/nationalarchives/notifications/messages/EventMessages.scala
src/test/scala/uk/gov/nationalarchives/notifications/CloudwatchAlarmIntegrationSpec.scala

This will initially be used for the DDOS alert Cloudwatch alarms we get
from AWS advanced shield but there's nothing to stop us setting up other
Cloudwatch alarms, in which case this will work for those as well.

Add Cloudwatch alarm notifications.

---

src/main/scala/uk/gov/nationalarchives/notifications/Lambda.scala
src/main/scala/uk/gov/nationalarchives/notifications/decoders/IncomingEvent.scala
src/main/scala/uk/gov/nationalarchives/notifications/decoders/TransformEngineV2Decoder.scala
src/main/scala/uk/gov/nationalarchives/notifications/messages/EventMessages.scala
src/test/scala/uk/gov/nationalarchives/notifications/TransformEngineV2RetryIntegrationSpec.scala

'tre-out' SNS topic message do not use 'message attributes'
SNS topic subscription filtering only works with 'message attributes'
Notifications lambda will need to provide filtering on the messages to ensure only the correct 'tre-out' message trigger a retry export message to 'tre-in' SNS topic

Filter 'tre-out' topic messages

---

src/main/scala/uk/gov/nationalarchives/notifications/decoders/TransformEngineV2Decoder.scala
src/test/scala/uk/gov/nationalarchives/notifications/LambdaIntegrationSpec.scala

TRE is expecting `resource-validation` but we are passing in `resourceValidation` this does the renaming

TDR-2390 Update TDR-TRE case class

---

src/main/scala/uk/gov/nationalarchives/notifications/messages/EventMessages.scala

Use scala way to get the CanonicalName to avoid '$' sign appearing in the end of the class name

Use scala way to get the CanonicalName to avoid '$' sign

---

src/test/scala/uk/gov/nationalarchives/notifications/CloudwatchAlarmIntegrationSpec.scala
src/test/scala/uk/gov/nationalarchives/notifications/EcrScanIntegrationSpec.scala
src/test/scala/uk/gov/nationalarchives/notifications/ExportIntegrationSpec.scala
src/test/scala/uk/gov/nationalarchives/notifications/GenericMessageIntegrationSpec.scala
src/test/scala/uk/gov/nationalarchives/notifications/KeycloakEventIntegrationSpec.scala
src/test/scala/uk/gov/nationalarchives/notifications/LambdaIntegrationSpec.scala
src/test/scala/uk/gov/nationalarchives/notifications/ParameterStoreExpiryEventSpec.scala
src/test/scala/uk/gov/nationalarchives/notifications/StepFunctionErrorIntegrationSpec.scala

- Encapsulate test events in case classes
- Specify defaults for different expected output types (`None` for `Optional`s, noop for stub context)

Notifications integration spec tests- readability refactor

---

src/main/scala/uk/gov/nationalarchives/notifications/Lambda.scala
src/main/scala/uk/gov/nationalarchives/notifications/decoders/DraftMetadataStepFunctionErrorDecoder.scala
src/main/scala/uk/gov/nationalarchives/notifications/decoders/IncomingEvent.scala
src/main/scala/uk/gov/nationalarchives/notifications/messages/EventMessages.scala
src/main/scala/uk/gov/nationalarchives/notifications/messages/Messages.scala
src/test/scala/uk/gov/nationalarchives/notifications/DraftMetadataStepFunctionErrorIntegrationSpec.scala

If an unexpected error occurs during the handling of the request in the DraftMetadataValidator lambda the error is handled an the reason is returned to the calling code (Draft metadata step function). An error will be surfaced to the user in the UI but to allow the team to be proactive in resolving bugs, this error that should never happen will be sent to the TDR slack if it is seen in production.

Tdrd 439 handle unexpected errors in tdr draft metadata validator lambda

---

README.md
src/main/scala/uk/gov/nationalarchives/notifications/messages/EventMessages.scala
src/test/scala/uk/gov/nationalarchives/notifications/EcrScanIntegrationSpec.scala
src/test/scala/uk/gov/nationalarchives/notifications/LambdaErrorSpec.scala

These are no longer relevant with the implementation of Wiz to provide details of vulnerabilities to a wider audience

Turn off email alerts for ECR scan events

---

src/main/resources/application.intg.conf
src/main/resources/application.prod.conf
src/main/resources/application.staging.conf
src/main/scala/uk/gov/nationalarchives/notifications/Lambda.scala
src/main/scala/uk/gov/nationalarchives/notifications/decoders/IncomingEvent.scala
src/main/scala/uk/gov/nationalarchives/notifications/decoders/UploadEventDecoder.scala
src/main/scala/uk/gov/nationalarchives/notifications/messages/EventMessages.scala
src/main/scala/uk/gov/nationalarchives/notifications/messages/Messages.scala
src/test/resources/application.conf
src/test/scala/uk/gov/nationalarchives/notifications/UploadIntegrationSpec.scala

Support SharePoint transfers where upload is undertaken by non-TDR web application
Users require notification of upload complete/failed so can continue transfer within TDR web application
No system should be sending these event messages so safe to make use of "place holder" template ids

Configure upload event notifications
